using namespace std;

string words1[24] = {
    "he ",
    "them ",
    "you ",
    "me ",
    "cum ",
    "my dick ",
    "the left ",
    "jannies ",
    "she ",
    "lain ",
    "/g/ anons ",
    "programmers ",
    "redditors ",
    "glowies ",
    "femboys ",
    "the chinese ",
    "whites ",
    "women ",
    "anime girls ",
    "jewish people ",
    "bros ",
    "freetards ",
    "itoddlers ",
    "soyboys ",
};

string words2[22] = {
    "when ",
    "existing ",
    "in Syria, vibing with ",
    "doing the needful ",
    "learning java with nagoor babu, weapon of java from durgasoft ",
    "taking programming pills and ",
    "btfoing itoddlers by ",
    "pooing in the loo so you can help sir with ",
    "riding with biden, ",
    "on their way to ",
    "engaging in cock and ball torture with ",
    "taking away your penis by ",
    "doing how to get your foreskin back strategy 1: ",
    "ascending to divine understanding by ",
    "riding the bandwagon of ",
    "installing autism as a dependency for ",
    "getting emergency penis reduction therapy after ",
    "losing all sanity by ",
    "getting lost in the matrix from too much ", 
    "feeling suicidal after 1 simple trick: ",
    "trying to remove their virginity by: "
};

string words3[34] = {
    "installing gentoo",
    "cooming to anime girls",
    "buttin' benis bin bagina :DDDDDD",
    "shitposting on /g/",
    "transitioning into an it",
    "trying on programming socks",
    "killing ",
    "Segmentation fault (core dumped)",
    "(do not research)",
    "rebooting richard stallman ",
    "Posting satania ",
    "ejaculating on a cpu ",
    "becoming a weapon of java",
    "fixing a clicking sdd ",
    "downloading ram ",
    "being mentally ill",
    "acting like a paranoid schizophrenic",
    "epically hacking their moms basement",
    "cleaning out the piss bottles",
    "farming good boy points",
    "finishing their daily contribution to the.. jar",
    "shitpstlibs.dll",
    "activating the templeOS subsystem for windows 98",
    "installing gnu+systemd",
    "just werking",
    "torrenting debotnetted CIA approved windows 11",
    "encrypting all anime girls ",
    "installing Arch to feel superior to other autists online",
    "YOU ARE NOT BEING TRACKED BY ANY GOVERNMENT NOR NON GOVERNMENTAL ENTITY, THIS WARNING IS ENSURE THAT YOU FEEL SAFE UNDER YOUR $CURRENT_PREMISES",
    "opening an ftp session with Terry Davis up in heaven",
    "getting ebic dubs",
    "telling incels to have sex",
    "installing linux",
};
